### ISSUE TITLE
Refine definition of references in MetCoOp CAP profile

### ISSUE THREAD

**Issue by petringo** [fmidev/metcoop-wg-backend#4]
Current description (partial):

> Clarification: UPDATE msgType must refer to all previous messages that it updates.

Requiring reference to _all_, even expired previous messages leads to _really_ long list of references on alerts that are being updated for a long period of time over original expiration.

Following changes to profile specification should be considered:

1. An `Update` message _should_ not refer to already expired alerts.
2. `Cancel` messages should be considered here as well.

**Comment by tervo** [comment]
I find these suggestions to be good. I'll apply them into the profile if no objections are raised in a week.

**Comment by tervo** [comment]
Done in https://git.smhi.se/metcoop/metcoop-cap-profile/blob/version-1.0/metcoop-cap-profile.md
