### ISSUE TITLE
Consider sender as urn:oid in MetCoOp CAP profile

### ISSUE THREAD

**Issue by petringo** [fmidev/metcoop-wg-backend#5]
Current description (partial):

> Format: WMO Organization ID (OID).

I would suggest to present the organization id as urn:oid instead of just oid value. For example use:

```
urn:oid:2.49.0.0.xxx.x
```

instead of

```
2.49.0.0.xxx.x
```

The suggested presentation would be self-explanatory. But doesn't have to be resolvable, as sender is merely used as a "namespace identifier" for cap document identifier.

**Comment by tervo** [comment]
urn:oid:2.49.0.0.xxx.x shall be used.

**Comment by mrauhala** [comment]
The correct one was urn:oid:2.49.0.1 according Elliot Christian. 1 is for message and 0 is for authority itself.

**Comment by petringo** [comment]
How is it here, is the \<sender> related to _authority_ or _message_? The CAP standard says that sender should identify globally the originator.

**Comment by mrauhala** [comment]
You are correct, we are talking about sender. My mistake. WMO position on <identifier> is urn:oid:2.49.0.1

**Comment by tervo** [comment]
Done in https://git.smhi.se/metcoop/metcoop-cap-profile/blob/master/metcoop-cap-profile.md#sender
