### ISSUE TITLE
Consider a prefix when referring to MetCoOp CAP profile in CAP code element

### ISSUE THREAD

**Issue by petringo** [fmidev/metcoop-wg-backend#7]
Current description (partial):
> Identifies the message as following MetCoOP CAP Standard, versioned.
>
> Format: Link to the versioned specification document.

Prefixing the url would help to recognize, which one of \<code> elements denotes a certain version of MetCoOp CAP profile. For example `profile:<url>`, `cap:profile:<url>` or `profile:cap:<url>`.

Even when the version of the profile is previously unknown to the end user, it should be possible to recognize a CAP document as a MetCoOp profiled document. This issue is related to #6.

**Comment by tervo** [comment]
Prefix is needed for machines.

Profile shall be used in form `profile:cap:<github-url>`

**Comment by tervo** [comment]
Done in https://git.smhi.se/metcoop/metcoop-cap-profile/blob/master/metcoop-cap-profile.md#code
